
package com.psp.practica.school;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-02-28T16:25:07.419+01:00
 * Generated source version: 3.3.5
 *
 */

public class School_SchoolSOAP_Server{

    protected School_SchoolSOAP_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new SchoolSOAPImpl();
        String address = "http://localhost:8081/ProyectoPSP/services/SchoolSOAP";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new School_SchoolSOAP_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
