
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.psp.practica.school;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-02-28T16:25:07.359+01:00
 * Generated source version: 3.3.5
 *
 */

@javax.jws.WebService(
                      serviceName = "School",
                      portName = "SchoolSOAP",
                      targetNamespace = "http://www.example.org/School/",
                      wsdlLocation = "file:/C:/Users/gemel/eclipse-workspace/ProyectoPSP/WebContent/WSDL-APP/WSDLFile.wsdl",
                      endpointInterface = "com.psp.practica.school.School")

public class SchoolSOAPImpl implements School {

    private static final Logger LOG = Logger.getLogger(SchoolSOAPImpl.class.getName());

    /* (non-Javadoc)
     * @see com.psp.practica.school.School#evaluacionDeAlumnoEnUnaAsignatura(com.psp.practica.school.EvaluationRequest parameters)*
     */
    public com.psp.practica.school.EvaluationResponse evaluacionDeAlumnoEnUnaAsignatura(EvaluationRequest parameters) {
        LOG.info("Executing operation evaluacionDeAlumnoEnUnaAsignatura");
        System.out.println(parameters);
        try {
            com.psp.practica.school.EvaluationResponse _return = new com.psp.practica.school.EvaluationResponse();
            _return.setGreet("Greet-2106794520");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.psp.practica.school.School#altaDeAsignaturas(com.psp.practica.school.SubjectRequest parameters)*
     */
    public com.psp.practica.school.SubjectResponse altaDeAsignaturas(SubjectRequest parameters) {
        LOG.info("Executing operation altaDeAsignaturas");
        System.out.println(parameters);
        try {
            com.psp.practica.school.SubjectResponse _return = new com.psp.practica.school.SubjectResponse();
            _return.setGreet("Greet288972910");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.psp.practica.school.School#altaDeAlumnos(com.psp.practica.school.StudentRequest parameters)*
     */
    public com.psp.practica.school.StudentResponse altaDeAlumnos(StudentRequest parameters) {
        LOG.info("Executing operation altaDeAlumnos");
        System.out.println(parameters);
        try {
            com.psp.practica.school.StudentResponse _return = new com.psp.practica.school.StudentResponse();
            _return.setGreet("Greet-1438809320");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
