package com.psp.practica.school;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-02-28T16:25:07.426+01:00
 * Generated source version: 3.3.5
 *
 */
@WebServiceClient(name = "School",
                  wsdlLocation = "file:/C:/Users/gemel/eclipse-workspace/ProyectoPSP/WebContent/WSDL-APP/WSDLFile.wsdl",
                  targetNamespace = "http://www.example.org/School/")
public class School_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/School/", "School");
    public final static QName SchoolSOAP = new QName("http://www.example.org/School/", "SchoolSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/gemel/eclipse-workspace/ProyectoPSP/WebContent/WSDL-APP/WSDLFile.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(School_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/gemel/eclipse-workspace/ProyectoPSP/WebContent/WSDL-APP/WSDLFile.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public School_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public School_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public School_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public School_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public School_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public School_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns School
     */
    @WebEndpoint(name = "SchoolSOAP")
    public School getSchoolSOAP() {
        return super.getPort(SchoolSOAP, School.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns School
     */
    @WebEndpoint(name = "SchoolSOAP")
    public School getSchoolSOAP(WebServiceFeature... features) {
        return super.getPort(SchoolSOAP, School.class, features);
    }

}
