package com.psp.practica.school;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-02-28T16:25:07.407+01:00
 * Generated source version: 3.3.5
 *
 */
@WebService(targetNamespace = "http://www.example.org/School/", name = "School")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface School {

    @WebMethod(operationName = "Evaluacion_de_alumno_en_una_asignatura", action = "http://www.example.org/School/Evaluacion_de_alumno_en_una_asignatura")
    @WebResult(name = "EvaluationResponse", targetNamespace = "http://www.example.org/School/", partName = "parameters")
    public EvaluationResponse evaluacionDeAlumnoEnUnaAsignatura(

        @WebParam(partName = "parameters", name = "EvaluationRequest", targetNamespace = "http://www.example.org/School/")
        EvaluationRequest parameters
    );

    @WebMethod(operationName = "Alta_de_asignaturas", action = "http://www.example.org/School/Alta_de_asignaturas")
    @WebResult(name = "SubjectResponse", targetNamespace = "http://www.example.org/School/", partName = "parameters")
    public SubjectResponse altaDeAsignaturas(

        @WebParam(partName = "parameters", name = "SubjectRequest", targetNamespace = "http://www.example.org/School/")
        SubjectRequest parameters
    );

    @WebMethod(operationName = "Alta_de_alumnos", action = "http://www.example.org/School/Alta_de_alumnos")
    @WebResult(name = "StudentResponse", targetNamespace = "http://www.example.org/School/", partName = "parameters")
    public StudentResponse altaDeAlumnos(

        @WebParam(partName = "parameters", name = "StudentRequest", targetNamespace = "http://www.example.org/School/")
        StudentRequest parameters
    );
}
